function getHistoricalKanaRegressionChecks() {
    return [
        { id: 'SYS-AUDIT-HISTORICAL-FULL-SIZE-SOKUON', suite: 'unit', rule: 'Historical mode treats a full-size つ before a geminatable consonant as ambiguous unless attested historical evidence resolves it', input: '立つて', expected: 'true', run: () => String(buildTranslationDiagnostics('立つて', '立つて', 'Tatsute', [{ surface_form: '立つて', pos: '動詞', value: 'tatsute', readingResolution: { source: 'tokenizer', confidence: 0.8, reading: 'たつて', candidates: [], flags: [], variantMappings: [] } }], { historicalKana: true }).requiresReview) },
        { id: 'R0-KANA-LARGE-TSU', suite: 'unit', rule: 'Full-size つ remains tsu by default in modern text unless historical evidence proves a sokuon reading', input: 'まつ', expected: 'matsu', run: () => convertToRomaji('まつ') },
        { id: 'CHECK-LONG-HISTORICAL-SPAN-11', suite: 'unit', rule: 'Historical-kana evidence spans are evidence-bounded rather than capped at ten tokens', input: '11-token historical span', expected: '11', run: () => { const original = runtimeState.historicalKanaEvidenceDictionary; const originalPrefixes = runtimeState.historicalKanaEvidencePrefixes; const surface = 'ゐゐゐゐゐゐゐゐゐゐゐ'; const tokens = Array.from(surface).map(value => ({ surface_form: value, pos: '名詞' })); try { runtimeState.historicalKanaEvidenceDictionary = new Map([[surface, { reading: 'いいいいいいいいいいい', source: 'qa' }]]); runtimeState.historicalKanaEvidencePrefixes = new Set(); addSurfacePrefixes(runtimeState.historicalKanaEvidencePrefixes, surface); return String(findLongestHistoricalKanaEvidence(tokens, 0)?.length || 0); } finally { runtimeState.historicalKanaEvidenceDictionary = original; runtimeState.historicalKanaEvidencePrefixes = originalPrefixes; } } },
        { id: 'HIST-WOKASHI', suite: 'historical', rule: 'Historical mode uses attested whole-word evidence instead of treating historical を as a particle', input: 'をかし', expected: 'Okashi' },
        { id: 'HIST-WIDO', suite: 'historical', rule: 'Historical mode resolves obsolete ゐ from attested word evidence', input: 'ゐど', expected: 'Ido' },
        { id: 'HIST-WIRU', suite: 'historical', rule: 'Historical mode resolves obsolete ゐ in a verb from attested word evidence', input: 'ゐる', expected: 'Iru' },
        { id: 'HIST-MAWIRU', suite: 'historical', rule: 'Historical mode resolves obsolete medial ゐ without changing the modern pipeline', input: 'まゐる', expected: 'Mairu' },
        { id: 'HIST-OMOHIDE', suite: 'historical', rule: 'Historical mode keeps a mixed-script historical lexical form together', input: '思ひ出を語る', expected: 'Omoide o Kataru' },
        { id: 'HIST-KOWE', suite: 'historical', rule: 'Historical evidence may repair a token boundary that overshoots into a following modern particle', input: 'こゑを聞く', expected: 'Koe o Kiku', expectedRequiresReview: false },
        { id: 'HIST-UWERU', suite: 'historical', rule: 'Historical mode resolves obsolete ゑ in a verb', input: '植ゑる', expected: 'Ueru' },
        { id: 'HIST-KANGAERU', suite: 'historical', rule: 'Historical mode maps attested へ spelling to the modern lexical reading without changing ordinary へ particles', input: '考へる', expected: 'Kangaeru' },
        { id: 'HIST-WOTOKO', suite: 'historical', rule: 'Historical mode distinguishes lexical を from the modern object particle', input: 'をとこ', expected: 'Otoko' },
        { id: 'HIST-TOWOKA', suite: 'historical', rule: 'Historical mode uses the attested 十日 spelling-to-reading relation', input: 'とをか', expected: 'Tooka' },
        { id: 'HIST-WODORU', suite: 'historical', rule: 'Historical mode resolves lexical initial を as modern お only for an attested historical word', input: 'をどる', expected: 'Odoru' },
        { id: 'HIST-AWOI', suite: 'historical', rule: 'Historical mode resolves an attested internal を without changing modern particle rules', input: 'あをい', expected: 'Aoi' },
        { id: 'HIST-OMOWAZU', suite: 'historical', rule: 'Historical mode resolves attested は to modern わ inside a lexical word', input: '思はず', expected: 'Omowazu' },
        { id: 'HIST-KEFU', suite: 'historical', rule: 'Historical mode resolves the attested historical spelling of 今日', input: 'けふは晴れ', expected: 'Kyou wa Hare' },
        { id: 'HIST-TEFU', suite: 'historical', rule: 'Historical mode resolves the attested historical spelling of 蝶', input: 'てふ', expected: 'Chou' },
        { id: 'HIST-IU', suite: 'historical', rule: 'Historical mode resolves 言ふ to the modern lexical reading いう', input: '言ふ', expected: 'Iu' },
        { id: 'HIST-YUUGATA', suite: 'historical', rule: 'Historical mode resolves the attested historical spelling of 夕方', input: 'ゆふがた', expected: 'Yuugata' },
        { id: 'HIST-KAGEROU', suite: 'historical', rule: 'Historical mode resolves final historical ふ from whole-word evidence', input: 'かげろふ', expected: 'Kagerou' },
        { id: 'HIST-FUKUROU', suite: 'historical', rule: 'Historical mode resolves final historical ふ from whole-word evidence', input: 'ふくろふ', expected: 'Fukurou' },
        { id: 'HIST-KAU', suite: 'historical', rule: 'Historical mode resolves historical 買ふ without inventing a global ふ conversion rule', input: '買ふ', expected: 'Kau' },
        { id: 'HIST-GUARD-WO', suite: 'historical', rule: 'Historical mode leaves an ordinary modern を particle unchanged', input: '本を読む', expected: 'Hon o Yomu' },
        { id: 'HIST-GUARD-HE', suite: 'historical', rule: 'Historical mode leaves an ordinary modern へ particle unchanged', input: '西へ進む', expected: 'Nishi e Susumu' },
        { id: 'HIST-GUARD-HA', suite: 'historical', rule: 'Historical mode leaves an ordinary modern は particle unchanged', input: '彼は学生', expected: 'Kare wa Gakusei' },
        { id: 'HIST-GUARD-KOUIU', suite: 'historical', rule: 'Historical mode does not replace modern written-vowel behaviour with phonetic normalisation', input: 'こういう', expected: 'Kouiu' },
        { id: 'HIST-GUARD-KONNICHIWA', suite: 'historical', rule: 'Historical mode preserves the modern lexicalised は pronunciation rule', input: 'こんにちは', expected: 'Konnichiwa' },
        { id: 'HIST-GUARD-NAME-WO', suite: 'historical', rule: 'Historical mode does not steal a modern を particle after a name-like token', input: 'みつを食べる', expected: 'Mitsu o Taberu' },
        { id: 'HIST-GUARD-NAME-HE', suite: 'historical', rule: 'Historical mode does not steal a modern へ particle after a name-like token', input: 'ふみへ行く', expected: 'Fumi e Iku' },
        { id: 'HIST-GUARD-KA-WA', suite: 'historical', rule: 'Historical mode does not invent a lexical かは conversion in an ordinary modern particle sequence', input: '行くかは分からない', expected: 'Iku ka wa Wakaranai' }
    ];
}
